namespace: tienda-online

postgres:
  image: mortviva7/ubpostgre:latest
  user: tienda
  password: tienda123
  database: tienda_online
  storageSize: 1Gi

backend:
  image: mortviva7/ubtiendaback:latest
  port: 3007
  nodePort: 30007
  jwtSecret: linas_jwt_secreto_3trimestre_2026
  jwtExpiresIn: 7d

frontend:
  image: mortviva7/ubtiendafront:latest
  port: 3008
  nodePort: 30008
  # URL que el NAVEGADOR usa para llamar al backend (IP pública del VPS)
  apiUrl: http://62.169.21.120:30007
