version: "3.8"

services:
  # SERVICIO WEB (REACT + NGINX)
  tarkov-web:
    image: mortviva7/ubreact:latest
    container_name: ctl_react
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/04_react/Dockerfile
    env_file: .env
    ports:
      - "3000:3000"  # Puerto para la App Vite
      - "1987:80"    # Puerto para Nginx (Producción)
      - "3462:22"    # SSH puerto único para evitar conflictos
    volumes:
      - ./logs:/root/logs
    networks:
      - red_proyectolinas
    restart: always

networks:
  red_proyectolinas:
    external: true