version: "3.8"

services:
  tarkov-web:
    image: mortviva7/ubreact:latest
    container_name: ctl_react_personal
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/04_react/Dockerfile
    env_file: .env
    ports:
      - "3010:3000"  # Primera entrada 
      - "3015:3000"  # SEGUNDA ENTRADA adicional
      - "8810:80"    # Nginx
      - "45678:22"   # SSH
    volumes:
      - ./logs:/root/logs
    networks:
      - red_proyectolinas
    restart: always

networks:
  red_proyectolinas:
    external: true