services:
  web:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/01_ubase/Dockerfile
    container_name: ctlinasbase
    image: mortviva7/ubbase
    ports:
      - "3456:22"
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      - red_proyectolinas

networks:
  red_proyectolinas:
    external: true
