version: '3.8'

services:
  portfolio:
    image: mortviva7/ubportfolio:latest 
    container_name: ctl_portfolio
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/05_portfolio/Dockerfile
    ports:
      - "5000:5000"
      - "1974:80"
      - "3463:22"
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs 
    networks:
      - red_proyectolinas
    restart: always

networks:
  red_proyectolinas:
    external: true