version: '3.8'

services:
  portfolio:
    image: mortviva7/ubportfolio:latest 
    container_name: ctl_portfolio_final
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/05_portfolio/Dockerfile
    ports:
      - "3011:5000"  # Primera entrada (la que querías)
      - "3012:5000"  # SEGUNDA ENTRADA (ahora tienes dos puertos para lo mismo)
      - "8811:80"    # Nginx
      - "45679:22"   # SSH
    env_file:
      - .env
    volumes:
      - ./logs:/root/logs 
    networks:
      - red_proyectolinas
    restart: always

networks:
  red_proyectolinas:
    external: true