FROM ubuntu:24.04

# Instalar básicos y SSH
RUN apt-get update && apt-get install -y curl git sudo nano net-tools iproute2 openssh-server && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/admin/base
WORKDIR /root/admin/base
RUN mkdir ./ssh
COPY ./common/id_rsa.pub  ./ssh/id_rsa.pub
COPY ./dockerfiles/01_ubase/admin/* .
RUN chmod +x ./start.sh

ENTRYPOINT [ "./start.sh" ]