apiVersion: v1
kind: Service
metadata:
  name: tienda-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: tienda-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      nodePort: {{ .Values.frontend.nodePort }}
  type: NodePort
