apiVersion: apps/v1
kind: Deployment
metadata:
  name: tienda-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: tienda-frontend
  template:
    metadata:
      labels:
        app: tienda-frontend
    spec:
      containers:
        - name: tienda-frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          env:
            - name: NEXT_PUBLIC_API_URL
              value: {{ .Values.frontend.apiUrl }}
