apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.postgre.credentials.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgre.credentials.password }}"
  POSTGRES_DB: "{{ .Values.postgre.credentials.database }}"
